In [2]:
# Install a pip comtradeapicall package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install --upgrade comtradeapicall

Collecting comtradeapicall
  Downloading comtradeapicall-1.0.20-py3-none-any.whl (20 kB)
Installing collected packages: comtradeapicall
Successfully installed comtradeapicall-1.0.20

In [3]:
import pandas
import requests
import comtradeapicall

In [4]:
subscription_key = '<YOUR KEY>' # comtrade api subscription key (from comtradedeveloper.un.org)
directory = 'output'  # output directory for downloaded files

In [5]:
#set some variables
from datetime import date
from datetime import timedelta
today = date.today()
yesterday = today - timedelta(days=1)
lastweek = today - timedelta(days=7)

In [6]:
# Call preview final data API to a data frame, max to 500 records, no subscription key required
# This example: Australia imports of commodity code 91 in classic mode in May 2022
mydf = comtradeapicall.previewFinalData(typeCode='C', freqCode='M', clCode='HS', period='202205',
                                        reporterCode='36', cmdCode='91', flowCode='M', partnerCode=None,
                                        partner2Code=None,
                                        customsCode=None, motCode=None, maxRecords=500, format_output='JSON',
                                        aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)

In [7]:
mydf.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,M,20220501,2022,5,202205,36,AUS,Australia,M,...,0.0,False,0.0,False,6.735064e+07,6.642209e+07,6.735064e+07,0,False,True
1,C,M,20220501,2022,5,202205,36,AUS,Australia,M,...,0.0,False,0.0,False,8.208810e+02,7.800080e+02,8.208810e+02,0,False,True
2,C,M,20220501,2022,5,202205,36,AUS,Australia,M,...,0.0,False,0.0,False,2.605931e+05,2.599554e+05,2.605931e+05,0,False,True
3,C,M,20220501,2022,5,202205,36,AUS,Australia,M,...,0.0,True,0.0,False,2.668635e+04,2.544649e+04,2.668635e+04,4,False,True
4,C,M,20220501,2022,5,202205,36,AUS,Australia,M,...,0.0,False,0.0,False,7.410397e+03,7.027445e+03,7.410397e+03,0,False,True

In [ ]:
# Call get final data API to a data frame, max to 250K records, subscription key required
# This example: Australia imports of commodity codes 90 and 91 from all partners in classic mode in May 2022
mydf = comtradeapicall.getFinalData(subscription_key, typeCode='C', freqCode='M', clCode='HS', period='202205',
                                    reporterCode='36', cmdCode='91,90', flowCode='M', partnerCode=None,
                                    partner2Code=None,
                                    customsCode=None, motCode=None, maxRecords=2500, format_output='JSON',
                                    aggregateBy=None, breakdownMode='classic', countOnly=None, includeDesc=True)